"""update articles table

Revision ID: 8231d15c168e
Revises: 49560768f142
Create Date: 2026-04-06 23:41:02.642957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8231d15c168e'
down_revision: Union[str, Sequence[str], None] = '49560768f142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('title', sa.String(length=1000), nullable=False))
    op.add_column('articles', sa.Column('url', sa.String(length=2000), nullable=False))
    op.alter_column('articles', 'duplicated_of_article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'duplicated_of_article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('articles', 'url')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'external_id')
    # ### end Alembic commands ###
